---
title: Freak Show
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  characters:
    title: characters
    output: false
subtitle: Join The Last Show
email: freakshowlarp@gmail.com
description: Freak Show is a LARP and a work of art that explores otherness. The participants
  will experience the last days and the final performance of the last freak show. This is
  a romantic horror story in the gothic style, about a family of outcasts and freaks
  struggling to survive in a hostile world. The freaks have made a deal with the promise
  of sanctuary and are practising for their performance, but what is the cost? In the end,
  as the last song fades away, the devil will come to take them all to perform for him forever.
baseurl:
url: http://freakshow.co/
author:
street_address:
city:
state:
zip_code:
country:
phone:
tiles-source: pages
tiles-count: 20
500px_url:
facebook_url: https://www.facebook.com/groups/freakshowlarp/
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:
markdown: kramdown
sass:
  sass_dir: _sass
